### ISSUE TITLE
Non-DOM events

### ISSUE THREAD

**Issue by starper** [alvart/proact#1]
Is there a way to deal with events, which source is not DOM, like, for example, socket events? If there is one, it would be nice to have an example.

**Comment by alvart** [comment]
I wrote an example showing how to use React's event handlers to respond to the URL change event in the proact-starter project: https://github.com/alvart/proact-starter/blob/master/src/app/Main.purs#L47

I'm pretty sure that with the `dispatcher'` function you can hook any `EventHandler` code you've written to any event, whether it's coming from the DOM or not. However, the example I gave above just shows how to hook an `EventHandler` to an "event signal", a philosophy coming from the Pux framework, so I hope that's enough to get you started :)

By the way, luckily the guys from Pux also have a library for Web Sockets that follows the same philosophy used in my routing example: https://github.com/bodil/purescript-signal-socket, so I'm pretty sure you could hook your event handlers in the same way I hooked my routing handlers.

**Comment by starper** [comment]
This is exactly what I wanted. Thanks.

**Comment by alvart** [comment]
Hey, just an update:

If you've following this project you might have noticed that there's a new version of it and along with it a new demo that showcases a chat application using websockets: https://github.com/alvart/proact-chat

The new release of the framework is very exciting because it accomplishes a total separation of side-effects from the web program, this in turns allows you to write pure code that is very easy to stub when simulating production environments.

I hope you can check it out some time soon in the future!
